Update sponsors for 2022
ausesa/ausesa.github.com pull request #79
Opened 2022-02-13 03:03 UTC by jyor212

2022-02-14 05:43 UTC, mjakeman commented
I'm not so sure about Salesforce's logo here. Can we use it like that?

![image](https://user-images.githubusercontent.com/12368711/153806612-3ab5ca5b-5bdd-402a-8081-bc486e4402c7.png)

We might want to align the baselines of Vista and VivCourt to avoid VivCourt's logo looking bigger.

![image](https://user-images.githubusercontent.com/12368711/153806774-48c01c80-63c4-4d58-94d2-bb1e8c4a8a44.png)

Otherwise looks good to me. Just need to clarify those

2022-02-14 05:44 UTC, mjakeman requested changes
See above

2022-02-14 05:50 UTC, jyor212 commented
> I'm not so sure about Salesforce's logo here. Can we use it like that?
> 
> ![image](https://user-images.githubusercontent.com/12368711/153806612-3ab5ca5b-5bdd-402a-8081-bc486e4402c7.png)
> 
> We might want to align the baselines of Vista and VivCourt to avoid VivCourt's logo looking bigger.
> 
> ![image](https://user-images.githubusercontent.com/12368711/153806774-48c01c80-63c4-4d58-94d2-bb1e8c4a8a44.png)
> 
> Otherwise looks good to me. Just need to clarify those

Same image was used in facebook post so assume it's ok?

2022-02-20 05:41 UTC, mjakeman approved these changes

2022-02-20 05:41 UTC, merged